// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwCS8z81BaeoT94MUApl7KjRf-U1PtPuo',
    appId: '1:801696569101:web:1c91310fee746219c18244',
    messagingSenderId: '801696569101',
    projectId: 'schedule-app-63d55',
    authDomain: 'schedule-app-63d55.firebaseapp.com',
    storageBucket: 'schedule-app-63d55.firebasestorage.app',
    measurementId: 'G-6CZ500HHEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfF8lG931BkFpBwID9brGu6mFzxRDMHkw',
    appId: '1:801696569101:android:1336fbdbe8d76d5bc18244',
    messagingSenderId: '801696569101',
    projectId: 'schedule-app-63d55',
    storageBucket: 'schedule-app-63d55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcnj-T_GcsJADHd-3GlyIDqls_SB2XJTQ',
    appId: '1:801696569101:ios:f5b075da3d837d8cc18244',
    messagingSenderId: '801696569101',
    projectId: 'schedule-app-63d55',
    storageBucket: 'schedule-app-63d55.firebasestorage.app',
    iosBundleId: 'com.example.scheduleAppGemini',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcnj-T_GcsJADHd-3GlyIDqls_SB2XJTQ',
    appId: '1:801696569101:ios:f5b075da3d837d8cc18244',
    messagingSenderId: '801696569101',
    projectId: 'schedule-app-63d55',
    storageBucket: 'schedule-app-63d55.firebasestorage.app',
    iosBundleId: 'com.example.scheduleAppGemini',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwCS8z81BaeoT94MUApl7KjRf-U1PtPuo',
    appId: '1:801696569101:web:c34bb43d41c3912fc18244',
    messagingSenderId: '801696569101',
    projectId: 'schedule-app-63d55',
    authDomain: 'schedule-app-63d55.firebaseapp.com',
    storageBucket: 'schedule-app-63d55.firebasestorage.app',
    measurementId: 'G-D7E1Y1FQFB',
  );
}